//
//  LineUpDao.swift
//  VistivAPP
//
//  Created by mobapp05 on 31/01/2019.
//  Copyright © 2019 Jorn Swift. All rights reserved.
//

import Foundation

class LineUpDao{
    
    var LineUp:[Podium]
    
    init() {
        
        //opvullen bands
        let ReelBigFish = Artist.init(naam: "Reel big fish", omschrijving: "Reel Big Fish is een ska-punk band uit Zuid-Californië. Ze waren een van de vele bands die het succes van No Doubt en Sublime volgden. Zoals de meeste van deze bands onderscheidden ze zich door overbewegelijke shows te geven, humor erin te gebruiken en ironische covers te maken. Ze braken door in de zomer van 1997, toen hun eerste single Sell Out het favoriete nummer van een moderne rockradiozender en MTV werd. Gevestigd in Huntington Beach, Californië, was Reel Big Fish een trio dat bestond uit zanger/gitarist Aaron Barrett, bassist Matt Wong en drummer Andrew Gonzales. In die fase was de band een doorsnee rockband met pop-metal neigingen. Na een aantal maanden ontdekte de band ska en besloten ze koperblazers aan de band toe te voegen. Reel Big Fish had een moeilijke tijd omdat het moeilijk was om goede bespelers van koperblazers te vinden. Het duurde een paar jaar voordat ze hun uiteindelijke samenstelling vonden, met Tavis Werts (trompet), Scott Klopfenstein (trompet, zanger), Grant Barry (trombone) en Dan Regan (trombone) tot stand kwam. Inmiddels hebben Tavis Werts en Grant Barry de band weer verlaten en is John Christianson daarvoor in de plaats gekomen. Ook Andrew Gonzales is gestopt en Ryland Steen heeft zijn plek achter de drums ingenomen.Met de oorspronkelijke samenstelling heeft Reel Big Fish zijn debuutalbum Everything Sucks opgenomen. Ze hebben het album zelf uitgebracht in 1995. Everything Sucks werd een underground hit in ska-punk- en schoolkringen. Door het succes van dit album, mocht Reel Big Fish een contract teken bij platenmaatschappij Mojo Records. Het eerste album dat ze onder dit contract maakte was Turn the Radio Off. Het album werd in augustus 1996 uitgebracht. Het jaar erna gingen ze op tournee. In 1997 werd Sell out een grote hit en het album kwam de top 100 binnen. In 1998 speelde de band een rol in de film BASEketball. Met hun cd We're Not Happy 'Til You're Not Happy uit 2005 werd hun succes nog eens versterkt. In 2006 brak de band met platenmaatschappij Jive Records. Eind 2006 kwam in eigen beheer de live verzamel-cd/dvd Our live album is better than your live album uit. In juli 2007 verscheen weer een studio cd Monkeys for nothin'and the chimps for free.", uur: "18:00-19:30", img: "ReelBigFish.jpg", music: "Song1")
        let Hootie = Artist.init(naam: "Hootie & The Blowfish", omschrijving: "Hootie & the Blowfish werd opgericht in 1986. Het kwartet ontmoette elkaar toen zij eerstejaarsstudenten waren aan de Universiteit van South Carolina in Columbia, South Carolina. Mark Bryan hoorde Darius Rucker zingen in de douches van de slaapzaal en was onder de indruk van zijn vocale vermogen. Ze besloten samen coversongs te gaan spelen onder de naam The Wolf Brothers. Uiteindelijk gingen ze samenwerken met Dean Felber, een voormalige middelbareschoolgenoot van Bryan, en Jim Soni Sonefeld en veranderde men de naam in Hootie & the Blowfish. Brantley Smith was de oorspronkelijke drummer. Hij verliet de groep na drie jaar, maar speelde sindsdien nog wel een enkele keer mee als gastmuzikant. De band bracht in eigen beheer twee demo EP's uit in 1991 en 1992. In 1993 kwam de EP Kootchypop uit. Ook deze EP werd in eigen beheer uitgebracht en gemaakt, in totaal zo'n 50.000 exemplaren. In augustus 1993 tekende de band een platencontract bij Atlantic Records. Andere platenmaatschappijen waren niet zo geïnteresseerd in de ondertekening van Hootie & the Blowfish omdat hun geluid nogal afweek ten opzichte van de grunge muziek die populair was in die tijd.", uur: "20:00-22:00", img: "HootietheBlowfish.jpg", music: "Song2")
        let TheWailers  = Artist.init(naam: "The Wailers", omschrijving: "The Wailers Band is de voormalige begeleidingsgroep van reggaezanger Bob Marley (vanaf 1974). De twee belangrijke leden van de band waren bassist Aston Family Man Barrett en zijn broer, de drummer Carlton Carlie Barrett. Verdere leden waren op leadgitaar Al Anderson, op keyboards Tyrone Downie en op percussie Alvin Seeco Patterson en als achtergrondzangeressen de I Threes (Judy Mowatt, Rita Marley en Marcia Griffiths). Na Bob Marley's overlijden in 1981 ging de band verder onder leiding van Junior Marvin, die ook de zang deed. Ook de bezetting wisselde wat. Tot aan de dood van Carlton Barrett in 1987 waren de twee broers de sturende factor in de muziekvorm. Sly Dunbar, een grote naam in de reggaewereld,[1] heeft het drummen met succes mogen leren van Carlton Carlie Barret. Ze brachten negen albums uit: I.D., Majestic Warriors, Jah Message, Heritage of Dub en vijf livealbums.", uur: "22:00-24:00", img: "wailers.jpg", music: "Song3")
        let LeftoverSalmon = Artist.init(naam: "Leftover Salmon", omschrijving: "Leftover Salmon is an American jam band from Boulder, Colorado, formed in 1989. The band's music is a blend of bluegrass, rock, country, and Cajun/Zydeco.The band formed in 1989, when members of the Salmon Heads, Vince Herman, Dave Dorian, and Gerry Cavagnaro, combined with members of the Left Hand String Band, Drew Emmitt and Glenn Keefe, to play a New Year's Eve show in 1989 at the Eldo in Crested Butte. Herman had previously played with Emmitt in the Left Hand String Band, and had called on his former bandmates Emmitt and Keefe to fill in for some missing members of the Salmon Heads for the New Year's Eve show. They chose the name Leftover Salmon on the drive to the show.", uur: "00:30-02:00", img: "Salmon.jpg", music: "Song4")
        let TheEels = Artist.init(naam: "The Eels", omschrijving: "Eels is de Amerikaanse band rond zanger/liedjesschrijver Mark Oliver Everett, die ook bekend is onder zijn artiestennaam E. De nummers variëren van rustige en tragische popballads tot energieke en optimistische rocknummers, met invloeden van blues en vaak de karakteristieke Wurlitzer-piano. Daarnaast spelen de melancholische teksten van E (vaak geïnspireerd door de talrijke tragische gebeurtenissen in zijn familie en/of directe omgeving) een belangrijke rol. Veel geroemd zijn de albums Beautiful Freak (1996), Electro-Shock Blues (1998) en Blinking Lights And Other Revelations (2005).", uur: "16:00-17:30", img: "the_eels.jpg", music: "Song5")
        let Mutiny = Artist.init(naam: "Mutiny", omschrijving: "Mutiny are an Australian folk punk band based in Melbourne. Their slogan is Folk punk for punk folk. They first formed in 1991 and have performed in Australia, Europe and the US. The original members were Chris Patches (vocals, drums), Greg Stainsby (guitar, mandolin), Briony Grigg (vocals, 12 string guitar), and Alice Green (bass). Chris originally sang in Melbourne crust band Compost. Greg and Alice were members of Melbourne punk band Insyte. Their songs tend to revolve around lives and issues of the working class and convicts, with a strong thread of Australian history throughout all of their releases. Their sound is often referred to as 'pirate' as their melding of folk sounds with punk imagery, politics and style gives many of their songs the feel of a jig. The use of a mandolin and piano accordion add to this feel as well. They have a strong anti-authoritarian philosophy and this comes out in their music and live shows. They played throughout the UK and Europe in 1994 and again through Europe in 1997. They also toured the United States in 1999. Greg Stainsby, Alice Green and Mark Jennings are currently also in The Currency.", uur: "18:00-19:00", img: "Mutiny.jpeg", music: "Song6")
        let PiratesForSail = Artist.init(naam: "Pirates for Sail", omschrijving: "Pirates for Sail, at your service! We’re a cantankerous crew of conniving cutthroats, a scurvy swarm of salty sea-snakes, and the most bilious, barnacle-bedecked band of blistered bilge-rats in Baltimore! And yet if you put us in front of an audience, we make beautiful music. Who ever would have suspected? We specialize in shanties and songs of the sea, but we’ll sing most anything that catches our fancy. We can rouse your spirits with a bawdy drinking song, or we can soothe your soul with a tear-jerking old ballad. Or we could always just steal your gold, drink all your booze, and be out of sight before the dawn. The choice is yours, really.", uur: "19:30-21:30", img: "Pirates.jpg", music: "Song7")
        let RumRebellion = Artist.init(naam: "Rum Rebellion", omschrijving: "Hailing from Portland, Oregon USA, Rum Rebellion is a peppery mix of Oi!, punk rock, and Celtic influences served up to you with a distinctive pirate twist. Comprised of members whose past musical endeavors include All Worked Up, Unstable Youth, P.R.O.B.L.E.M.S., Fire At Will, and Heathen Shrine, Rum Rebellion has transformed from humble street corner busking roots into a widely known touring act. Our DIY attitude has powered us through endless shows and countless tours, and our dedication to bringing our best to every show has helped put the Pacific Northwest as well as our self-proclaimed Oi!Rish sub-genre on the map world wide.", uur: "21:00-22:30", img: "rumrebellion.jpg", music: "Song8")
        let PirateSpaceship = Artist.init(naam: "Pirate Spaceship", omschrijving: "As You Know, Space Is an Ocean, so it's only logical that it must have pirates as well. Depending how you view the future, lawlessness will always be present in society. There's always going to be a shadier, nastier way of doing business, and that will almost certainly follow humanity to the stars. Thus, sci-fi authors will include Expies of modern and historic un/organized crime, be they space mafia, gangs, or—in our case—pirates.", uur: "23:00-01:00", img: "Spaceship.jpg", music: "Song9")
        
        //Podiums opvullen
        
        let BigFishStage = Podium.init(naam: "Big Fish Stage")
        BigFishStage.artistLijst! += [TheEels, ReelBigFish, Hootie, TheWailers, LeftoverSalmon]
        
        let PirateStage = Podium.init(naam: "Pirate Stage")
        PirateStage.artistLijst! += [Mutiny, PiratesForSail, RumRebellion, PirateSpaceship]
        
        
        
    
        
        //Line up afmaken
        
        self.LineUp = [BigFishStage, PirateStage]
        
    }
}
